"""
Multi-Curriculum Standard Ontology Mapper.
Maps the 26-node Algebra/Quadratic Knowledge DAG to international curriculum standards:
- Türkiye MEB (Milli Eğitim Bakanlığı)
- IB DP Mathematics (Analysis & Approaches AA, Applications & Interpretation AI)
- US Common Core State Standards (CCSS Math)
- AP Precalculus (College Board)
"""

from __future__ import annotations
from typing import Dict, List, Optional
from app.models.schemas import CurriculumStandard


class CurriculumOntologyRegistry:
    """Registry maintaining cross-curriculum alignment across all 110 DAG nodes."""

    CURRICULA = ["MEB", "IB_AA", "IB_AI", "CCSS", "AP_PRECALC", "AP_CALC"]

    def __init__(self):
        self._standards: Dict[str, List[CurriculumStandard]] = {}
        self._build_standards()

    def _build_standards(self) -> None:
        raw_standards = [
            # N01: Negatif Sayılarla İşlemler
            CurriculumStandard(
                standard_id="MEB-7.1.1.1",
                curriculum="MEB",
                node_id="N01",
                title_tr="Tam Sayılarla Çarpma ve Bölme İşlemleri",
                title_en="Operations with Integers and Signed Numbers",
                description_tr="Tam sayılarla çarpma ve bölme işlemlerini yapar, işaret kurallarını kavrar.",
                description_en="Multiply and divide integers; understand signs and absolute value.",
                grade_level="7",
            ),
            CurriculumStandard(
                standard_id="CCSS-7.NS.A.1",
                curriculum="CCSS",
                node_id="N01",
                title_tr="Rasyonel Sayılarla Toplama ve Çıkarma",
                title_en="Operations with Negative Integers and Rational Numbers",
                description_tr="Negatif sayılar ve rasyonel işlemler kuralları.",
                description_en="Apply and extend previous understandings of addition and subtraction to add and subtract rational numbers.",
                grade_level="Grade 7",
            ),

            # N04: Lineer Denklem Çözme
            CurriculumStandard(
                standard_id="MEB-8.2.2.1",
                curriculum="MEB",
                node_id="N04",
                title_tr="Birinci Dereceden Bir Bilinmeyenli Denklemler",
                title_en="Linear Equations in One Variable",
                description_tr="Birinci dereceden bir bilinmeyenli denklemleri çözer.",
                description_en="Solve linear equations in one variable with rational number coefficients.",
                grade_level="8",
            ),
            CurriculumStandard(
                standard_id="CCSS-HSA-REI.B.3",
                curriculum="CCSS",
                node_id="N04",
                title_tr="Birinci Dereceden Denklemleri Çözme",
                title_en="Solve Linear Equations and Inequalities",
                description_tr="Tek değişkenli doğrusal denklemleri çözer.",
                description_en="Solve linear equations and inequalities in one variable, including equations with coefficients represented by letters.",
                grade_level="High School",
            ),

            # N06: İki Kare Farkı
            CurriculumStandard(
                standard_id="MEB-8.2.1.3",
                curriculum="MEB",
                node_id="N06",
                title_tr="Özdeşlikler ve İki Kare Farkı",
                title_en="Difference of Two Squares Identity",
                description_tr="a² - b² = (a - b)(a + b) özdeşliğini modeller ve cebirsel olarak uygular.",
                description_en="Factor algebraic expressions using the difference of two squares pattern.",
                grade_level="8",
            ),
            CurriculumStandard(
                standard_id="IB-AA-SL-1.2",
                curriculum="IB_AA",
                node_id="N06",
                title_tr="Cebirsel İfadelerin Çarpanlara Ayrılması",
                title_en="Algebraic Manipulation and Factorization",
                description_tr="Özdeşlikler ve çarpanlara ayırma.",
                description_en="Algebraic manipulation of quadratic and polynomial forms.",
                grade_level="DP1",
            ),

            # N08: Monik Üçterimlileri Çarpanlara Ayırma
            CurriculumStandard(
                standard_id="MEB-10.3.2.1",
                curriculum="MEB",
                node_id="N08",
                title_tr="Polinom ve Üçterimlilerin Çarpanlara Ayrılması",
                title_en="Factoring Monic Quadratic Trinomials",
                description_tr="x² + bx + c biçimindeki ifadeleri çarpanlarına ayırır.",
                description_en="Factor trinomials of the form x^2 + bx + c.",
                grade_level="10",
            ),
            CurriculumStandard(
                standard_id="CCSS-HSA-SSE.B.3.A",
                curriculum="CCSS",
                node_id="N08",
                title_tr="Kökleri Belirlemek İçin Çarpanlara Ayırma",
                title_en="Factor Quadratic Expression to Reveal Zeros",
                description_tr="Kökleri ortaya çıkarmak için ikinci dereceden ifadeleri çarpanlarına ayırır.",
                description_en="Factor a quadratic expression to reveal the zeros of the function it defines.",
                grade_level="High School",
            ),

            # N10: İkinci Dereceden Denklem Standart Formu
            CurriculumStandard(
                standard_id="MEB-10.4.1.1",
                curriculum="MEB",
                node_id="N10",
                title_tr="İkinci Dereceden Denklem Tanımı ve Standart Form",
                title_en="Quadratic Equations in Standard Form",
                description_tr="ax² + bx + c = 0 formundaki denklemleri tanır ve temel kavramlarını açıklar.",
                description_en="Recognize and manipulate quadratic equations in standard form ax^2 + bx + c = 0.",
                grade_level="10",
            ),
            CurriculumStandard(
                standard_id="IB-AA-SL-2.1",
                curriculum="IB_AA",
                node_id="N10",
                title_tr="Kuadratik Fonksiyonlar ve Denklemler",
                title_en="Quadratic Models and Equations",
                description_tr="Kuadratik fonksiyon ve denklemlerin temel özellikleri.",
                description_en="The quadratic function and forms: standard form, factorized form, vertex form.",
                grade_level="DP1",
            ),

            # N12: Çarpanlara Ayırma ile Çözüm
            CurriculumStandard(
                standard_id="MEB-10.4.1.1.A",
                curriculum="MEB",
                node_id="N12",
                title_tr="Çarpanlara Ayırma Yöntemi ile Denklem Çözme",
                title_en="Solving Quadratics by Factoring",
                description_tr="İkinci dereceden bir bilinmeyenli denklemleri çarpanlara ayırma ile çözer.",
                description_en="Solve quadratic equations by applying the zero-product property to factored forms.",
                grade_level="10",
            ),
            CurriculumStandard(
                standard_id="CCSS-HSA-REI.B.4.B",
                curriculum="CCSS",
                node_id="N12",
                title_tr="İkinci Dereceden Denklemleri Çözme",
                title_en="Solve Quadratic Equations by Inspection and Factoring",
                description_tr="Gözlem ve çarpanlara ayırma ile ikinci dereceden denklemleri çözer.",
                description_en="Solve quadratic equations by inspection, taking square roots, and factoring.",
                grade_level="High School",
            ),

            # N15: Cebirsel Tam Kareye Tamamlama
            CurriculumStandard(
                standard_id="MEB-10.4.1.1.B",
                curriculum="MEB",
                node_id="N15",
                title_tr="Tam Kareye Tamamlama Yöntemi",
                title_en="Completing the Square Method",
                description_tr="İkinci dereceden denklemleri tam kareye tamamlayarak çözer.",
                description_en="Solve quadratic equations by completing the square.",
                grade_level="10",
            ),
            CurriculumStandard(
                standard_id="CCSS-HSA-REI.B.4.A",
                curriculum="CCSS",
                node_id="N15",
                title_tr="Tam Kareye Tamamlama",
                title_en="Use Completing the Square to Solve Quadratics",
                description_tr="ax² + bx + c = 0 formunu (x - p)² = q formuna dönüştürür.",
                description_en="Use the method of completing the square to transform any quadratic equation into an equation of the form (x - p)^2 = q.",
                grade_level="High School",
            ),
            CurriculumStandard(
                standard_id="IB-AI-SL-2.4",
                curriculum="IB_AI",
                node_id="N15",
                title_tr="Kuadratik Modeller ve Dönüşümler",
                title_en="Quadratic Models and Vertex Transformations",
                description_tr="Tam kare formuna getirerek modelleme.",
                description_en="Quadratic models, vertex form by completing the square.",
                grade_level="DP1",
            ),

            # N18: Kuadratik Formülün Standart Uygulanışı
            CurriculumStandard(
                standard_id="MEB-10.4.1.1.C",
                curriculum="MEB",
                node_id="N18",
                title_tr="Kuadratik Formül ile Kök Bulma",
                title_en="Quadratic Formula Solution",
                description_tr="Kuadratik formülü kullanarak denklemin köklerini bulur.",
                description_en="Apply the quadratic formula x = (-b +- sqrt(b^2 - 4ac)) / (2a).",
                grade_level="10",
            ),
            CurriculumStandard(
                standard_id="IB-AA-SL-2.1.B",
                curriculum="IB_AA",
                node_id="N18",
                title_tr="Kuadratik Formül ve Kökler",
                title_en="The Quadratic Formula and Exact Roots",
                description_tr="Kuadratik formül ve rasyonel/irrasyonel kökler.",
                description_en="Use of the quadratic formula to find exact roots.",
                grade_level="DP1",
            ),

            # N20: Diskriminant ve Kök Türü İlişkisi
            CurriculumStandard(
                standard_id="MEB-10.4.1.1.D",
                curriculum="MEB",
                node_id="N20",
                title_tr="Diskriminantın Kök Varlığı ile İlişkisi",
                title_en="Nature of Roots via Discriminant",
                description_tr="Δ = b² - 4ac değerine göre reel ve karmaşık kök durumlarını inceler.",
                description_en="Determine the number and nature of roots using the discriminant Delta = b^2 - 4ac.",
                grade_level="10",
            ),
            CurriculumStandard(
                standard_id="IB-AA-SL-2.1.C",
                curriculum="IB_AA",
                node_id="N20",
                title_tr="Diskriminant Analizi (Δ)",
                title_en="The Discriminant Delta and Nature of Roots",
                description_tr="Δ > 0, Δ = 0 ve Δ < 0 durumları.",
                description_en="The discriminant Delta = b^2 - 4ac and the nature of the roots: two distinct real roots, two equal real roots, no real roots.",
                grade_level="DP1",
            ),

            # N21-N23: İkinci Dereceden Eşitsizlikler
            CurriculumStandard(
                standard_id="MEB-11.3.2.1",
                curriculum="MEB",
                node_id="N21",
                title_tr="İkinci Dereceden Eşitsizlikler ve Çözüm Kümeleri",
                title_en="Quadratic Inequalities and Sign Tables",
                description_tr="ax² + bx + c ≶ 0 eşitsizliklerinin işaret tablosu ile çözümünü yapar.",
                description_en="Solve quadratic inequalities in one variable using sign charts.",
                grade_level="11",
            ),
            CurriculumStandard(
                standard_id="IB-AA-HL-2.1",
                curriculum="IB_AA",
                node_id="N22",
                title_tr="Eşitsizliklerin Analitik Çözümü",
                title_en="Analytical and Graphical Solution of Inequalities",
                description_tr="Kuadratik eşitsizliklerin analitik ve grafiksel çözümü.",
                description_en="Solving quadratic inequalities analytically and graphically.",
                grade_level="DP2",
            ),

            # N24-N26: Parabol ve Fonksiyon Dönüşümleri
            CurriculumStandard(
                standard_id="MEB-11.3.1.2",
                curriculum="MEB",
                node_id="N24",
                title_tr="İkinci Dereceden Fonksiyon Grafiği (Parabol)",
                title_en="Quadratic Functions and Parabola Graphs",
                description_tr="Parabolün tepe noktası, simetri ekseni ve eksen kesimlerini belirler.",
                description_en="Determine vertex, axis of symmetry, and intercepts of parabolas.",
                grade_level="11",
            ),
            CurriculumStandard(
                standard_id="AP-PRECALC-1.2",
                curriculum="AP_PRECALC",
                node_id="N25",
                title_tr="Polinom ve Kuadratik Fonksiyonlarda Değişim",
                title_en="Rates of Change in Quadratic and Polynomial Functions",
                description_tr="Kuadratik modellerde ortalama değişim hızı ve tepe noktası dönüşümleri.",
                description_en="Examine vertex transformations f(x) = a(x-h)^2 + k and rates of change in quadratic models.",
                grade_level="Grade 11-12",
            ),
            # N27-N38: İleri Parabol ve Optimizasyon
            CurriculumStandard(
                standard_id="MEB-11.3.1.3",
                curriculum="MEB",
                node_id="N32",
                title_tr="İkinci Dereceden Fonksiyonlarda Ekstremum ve Optimizasyon",
                title_en="Extrema and Optimization in Quadratic Functions",
                description_tr="Parabolün en büyük ve en küçük değerini belirleyerek gerçek hayat problemlerine uygular.",
                description_en="Determine maximum and minimum values of quadratic functions and apply to real-world modeling.",
                grade_level="11",
            ),
            CurriculumStandard(
                standard_id="IB-AA-SL-2.4",
                curriculum="IB_AA",
                node_id="N33",
                title_tr="Parabol ile Doğrunun Kesişimleri",
                title_en="Intersections of Lines and Quadratic Curves",
                description_tr="Doğru ile parabolün kesişim noktalarını ve teğetlik şartını discriminant ile inceler.",
                description_en="Find points of intersection between straight lines and parabolas using the discriminant.",
                grade_level="DP1",
            ),
            # N39-N50: Polinomlar ve Polinom Cebiri
            CurriculumStandard(
                standard_id="MEB-10.3.1.1",
                curriculum="MEB",
                node_id="N39",
                title_tr="Polinom Kavramı ve Derece",
                title_en="Polynomial Concept, Degree, and Leading Coefficients",
                description_tr="Bir değişkenli polinom kavramını açıklar, derece, katsayı ve sabit terimi belirler.",
                description_en="Define single-variable polynomials, identify degree, leading coefficient, and constant term.",
                grade_level="10",
            ),
            CurriculumStandard(
                standard_id="MEB-10.3.1.2",
                curriculum="MEB",
                node_id="N42",
                title_tr="Polinomlarda Kalan Teoremi",
                title_en="Polynomial Remainder Theorem",
                description_tr="P(x) polinomunun (x - a) ve (ax + b) ile bölümünden kalanı bölme yapmadan bulur.",
                description_en="Find remainders of polynomial divisions without explicit division using the Remainder Theorem.",
                grade_level="10",
            ),
            CurriculumStandard(
                standard_id="IB-AA-HL-1.4",
                curriculum="IB_AA",
                node_id="N47",
                title_tr="Polinomlarda Çarpan Teoremi ve Kökler",
                title_en="Factor Theorem and Roots of Polynomials",
                description_tr="Çarpan teoremini kullanarak polinomları çarpanlarına ayırır ve kökleri tespit eder.",
                description_en="Apply the Factor Theorem to factorize polynomials and find exact real and complex roots.",
                grade_level="DP1",
            ),
            CurriculumStandard(
                standard_id="AP-PRECALC-1.3",
                curriculum="AP_PRECALC",
                node_id="N49",
                title_tr="Polinom Fonksiyon Grafikleri ve Katlı Kökler",
                title_en="Polynomial Graphs, Multiplicity, and End Behavior",
                description_tr="Kök katlılığına göre grafiğin x-eksenini kesme veya teğet olma durumunu ve limit davranışını inceler.",
                description_en="Analyze polynomial graphs, root multiplicity (tangency vs crossing), and asymptotic end behavior.",
                grade_level="Grade 11-12",
            ),
            # N51-N65: Trigonometri Standartları
            CurriculumStandard(
                standard_id="MEB-11.1.1.1",
                curriculum="MEB",
                node_id="N51",
                title_tr="Yönlü Açılar ve Açı Ölçü Birimleri",
                title_en="Directed Angles and Unit Conversion",
                description_tr="Yönlü açı kavramını açıklar, derece ve radyan cinsinden esas ölçüyü hesaplar.",
                description_en="Explain directed angles, convert between degrees and radians, and find coterminal principle angles.",
                grade_level="11",
            ),
            CurriculumStandard(
                standard_id="IB-AA-SL-3.1",
                curriculum="IB_AA",
                node_id="N52",
                title_tr="Birim Çember ve Trigonometrik Oranlar",
                title_en="The Unit Circle and Trigonometric Coordinates",
                description_tr="Birim çember üzerinde sinüs ve kosinüs koordinatlarını tanımlar.",
                description_en="The unit circle: cosine and sine as coordinates of points on the circle of radius 1.",
                grade_level="DP1",
            ),
            CurriculumStandard(
                standard_id="MEB-11.1.2.1",
                curriculum="MEB",
                node_id="N53",
                title_tr="Temel Trigonometrik Özdeşlikler",
                title_en="Fundamental Trigonometric Identities",
                description_tr="Pisagor trigonometrik özdeşliği ve oran bağıntılarını kullanarak sadeleştirme yapar.",
                description_en="Simplify expressions using Pythagorean identities and ratio definitions.",
                grade_level="11",
            ),
            CurriculumStandard(
                standard_id="AP-PRECALC-3.2",
                curriculum="AP_PRECALC",
                node_id="N55",
                title_tr="Trigonometrik İndirgeme ve Referans Açıları",
                title_en="Reference Angles and Symmetry Reductions",
                description_tr="Referans açıları ve simetri kullanarak trigonometrik oranları 1. bölgeye indirger.",
                description_en="Use reference angles and symmetry across quadrants to evaluate trigonometric values.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="IB-AA-SL-3.5",
                curriculum="IB_AA",
                node_id="N60",
                title_tr="Toplam ve Fark Formülleri",
                title_en="Compound Angle Identities",
                description_tr="Sinüs ve kosinüs için toplam-fark formüllerini uygular.",
                description_en="Double angle and compound angle identities for sine and cosine.",
                grade_level="DP1",
            ),
            # N66-N80: Üstel ve Logaritmik Fonksiyon Standartları
            CurriculumStandard(
                standard_id="MEB-12.1.1.1",
                curriculum="MEB",
                node_id="N66",
                title_tr="Üstel Fonksiyon ve Grafiği",
                title_en="Exponential Functions and Graphs",
                description_tr="Üstel fonksiyonu açıklar, grafiğini çizer ve özelliklerini yorumlar.",
                description_en="Define exponential functions, sketch graphs, and interpret monotonic growth/decay behavior.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="IB-AI-SL-3.1",
                curriculum="IB_AI",
                node_id="N67",
                title_tr="Üstel Büyüme ve Bozulma Modelleri",
                title_en="Exponential Growth and Decay Models",
                description_tr="Gerçek hayat popülasyon ve finans verilerini üstel modellerle analiz eder.",
                description_en="Model real-world natural growth and decay processes using exponential functions.",
                grade_level="DP1",
            ),
            CurriculumStandard(
                standard_id="MEB-12.1.2.1",
                curriculum="MEB",
                node_id="N69",
                title_tr="Logaritma Fonksiyonu Tanımı ve Tersi",
                title_en="Logarithmic Function as Inverse of Exponential",
                description_tr="Logaritma fonksiyonunu üstel fonksiyonun tersi olarak tanımlar ve grafiksel simetriyi gösterir.",
                description_en="Define logarithms as the inverse of exponential functions with domain restrictions.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-PRECALC-2.4",
                curriculum="AP_PRECALC",
                node_id="N72",
                title_tr="Logaritmik Özellikler (Çarpım, Bölüm, Kuvvet)",
                title_en="Logarithmic Rules and Expansions",
                description_tr="Logaritmanın çarpım, bölüm ve kuvvet kurallarını cebirsel dönüşümlerde kullanır.",
                description_en="Apply product, quotient, and power rules of logarithms to expand and condense expressions.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.1.2.2",
                curriculum="MEB",
                node_id="N74",
                title_tr="Taban Değiştirme Kuralı ve Uygulamaları",
                title_en="Change of Base Rule in Logarithms",
                description_tr="Logaritmada taban değiştirme kuralını uygular ve sayısal hesaplamalarda kullanır.",
                description_en="Convert logarithms across bases using the change of base identity.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="IB-AA-SL-1.3",
                curriculum="IB_AA",
                node_id="N78",
                title_tr="Logaritmik ve Üstel Denklemler",
                title_en="Logarithmic Equations and Extraneous Roots",
                description_tr="Logaritma denklemlerini çözer ve yabancı kökleri tanım kümesi denetimiyle eler.",
                description_en="Solve exponential and logarithmic equations analytically, filtering extraneous solutions.",
                grade_level="DP1",
            ),
            CurriculumStandard(
                standard_id="AP-PRECALC-2.15",
                curriculum="AP_PRECALC",
                node_id="N80",
                title_tr="Yarı-Logaritmik ve Logaritmik Modelleme",
                title_en="Semi-Log and Logarithmic Scales in Science",
                description_tr="pH, ses şiddeti ve Richter ölçeği gibi logaritmik skalaları matematiksel modeller.",
                description_en="Apply logarithmic functions to scientific scales including decibels, pH, and earthquake magnitudes.",
                grade_level="Grade 11-12",
            ),
            # SEVİYE 10: Limit & Süreklilik (N81 - N88)
            CurriculumStandard(
                standard_id="MEB-12.5.1.1",
                curriculum="MEB",
                node_id="N81",
                title_tr="Limit Kavramı ve Tek Taraflı Limitler",
                title_en="Intuitive Limits and One-Sided Limits",
                description_tr="Bir noktaya sağdan ve soldan yaklaşarak limitin varlığını inceler.",
                description_en="Explore intuitive concept of limits and examine left-hand and right-hand limits.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-1.3",
                curriculum="AP_CALC",
                node_id="N81",
                title_tr="Limitleri Grafik ve Tablolardan Tahmin Etme",
                title_en="Estimating Limits from Graphs and Tables",
                description_tr="Grafik ve sayısal değer tabloları üzerinden limit davranışını tahmin eder.",
                description_en="Estimate limits of functions using graphical and tabular representations.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.5.1.2",
                curriculum="MEB",
                node_id="N82",
                title_tr="Limit Cebirsel Özellikleri",
                title_en="Algebraic Properties of Limits",
                description_tr="Toplam, fark, çarpım ve bölüm limit özelliklerini kullanarak limit hesaplar.",
                description_en="Calculate limits using fundamental algebraic limit properties and direct substitution.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-1.5",
                curriculum="AP_CALC",
                node_id="N82",
                title_tr="Cebirsel Limit Belirleme",
                title_en="Determining Limits Using Algebraic Properties",
                description_tr="Limit kurallarını ve doğrudan yerine koyma yöntemini uygular.",
                description_en="Determine limits using algebraic manipulation and limit laws.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.5.1.3",
                curriculum="MEB",
                node_id="N83",
                title_tr="0/0 Belirsizliği ve Çarpanlara Ayırma",
                title_en="0/0 Indeterminate Form and Factoring",
                description_tr="Rasyonel fonksiyonlarda 0/0 belirsizliğini çarpanlara ayırma ile giderir.",
                description_en="Resolve 0/0 indeterminate forms using polynomial factorization and cancellation.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="IB-AA-SL-5.2",
                curriculum="IB_AA",
                node_id="N83",
                title_tr="Analitik Limit ve Belirsizlikler",
                title_en="Analytical Evaluation of Indeterminate Limits",
                description_tr="0/0 belirsizliğini cebirsel yöntemlerle çözümler.",
                description_en="Evaluate limits analytically when encountering 0/0 indeterminate forms.",
                grade_level="DP1",
            ),
            CurriculumStandard(
                standard_id="MEB-12.5.1.4",
                curriculum="MEB",
                node_id="N85",
                title_tr="Trigonometrik Fonksiyonların Limitleri",
                title_en="Limits of Trigonometric Functions",
                description_tr="lim(x->0) sin(x)/x = 1 özel limiti ve trigonometrik belirsizlikleri çözer.",
                description_en="Evaluate trigonometric limits using standard identities and squeeze theorem.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.5.2.1",
                curriculum="MEB",
                node_id="N87",
                title_tr="Bir Noktada Süreklilik",
                title_en="Continuity at a Point",
                description_tr="Fonksiyonun bir noktadaki sürekliliğini limit ve fonksiyon değeri eşitliğiyle inceler.",
                description_en="Define continuity at a point and classify removable/jump discontinuities.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-1.10",
                curriculum="AP_CALC",
                node_id="N87",
                title_tr="Süreklilik Koşulları ve Süreksizlik Türleri",
                title_en="Defining Continuity at a Point and Classifying Discontinuities",
                description_tr="Limit, tanım ve eşitlik şartlarını sağlayarak sürekliliği denetler.",
                description_en="Verify three-part definition of continuity and analyze point discontinuities.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.5.2.2",
                curriculum="MEB",
                node_id="N88",
                title_tr="Aralıkta Süreklilik ve Ara Değer Teoremi",
                title_en="Continuity on Intervals and Intermediate Value Theorem",
                description_tr="Sürekli fonksiyonların özelliklerini ve ara değer teoreminin kök varlığı uygulamasını açıklar.",
                description_en="Apply the Intermediate Value Theorem to guarantee roots on closed intervals.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-1.16",
                curriculum="AP_CALC",
                node_id="N88",
                title_tr="Ara Değer Teoremi (IVT)",
                title_en="Working with the Intermediate Value Theorem",
                description_tr="Kapalı aralıkta sürekli fonksiyonlar için IVT uygular.",
                description_en="Apply the Intermediate Value Theorem to justify existence of intermediate values and zeros.",
                grade_level="Grade 11-12",
            ),
            # SEVİYE 11: Türev Alma Kuralları (N89 - N98)
            CurriculumStandard(
                standard_id="MEB-12.6.1.1",
                curriculum="MEB",
                node_id="N89",
                title_tr="Türevin Limit Tanımı ve Anlık Değişim Oranı",
                title_en="Limit Definition of Derivative and Instantaneous Rate of Change",
                description_tr="Türevi fark oranının limiti olarak tanımlar ve geometrik anlamını yorumlar.",
                description_en="Define derivative as limit of difference quotient and interpret physically/geometrically.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-2.1",
                curriculum="AP_CALC",
                node_id="N89",
                title_tr="Ortalama ve Anlık Değişim Oranı",
                title_en="Defining Average and Instantaneous Rates of Change",
                description_tr="Sekant doğrusu eğiminden teğet doğrusu eğimine limit geçişini modeller.",
                description_en="Connect secant slope with tangent slope through the limit of difference quotients.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="IB-AA-SL-5.3",
                curriculum="IB_AA",
                node_id="N89",
                title_tr="Türevin Sezgisel ve Limit Tanımı",
                title_en="Derivative Defined from First Principles",
                description_tr="İlk ilkelerden türev alma yöntemini uygular.",
                description_en="Differentiate functions from first principles using difference quotients.",
                grade_level="DP1",
            ),
            CurriculumStandard(
                standard_id="MEB-12.6.1.2",
                curriculum="MEB",
                node_id="N90",
                title_tr="Kuvvet Kuralı ve Polinomların Türevi",
                title_en="Power Rule and Polynomial Differentiation",
                description_tr="x^n fonksiyonunun türevini n*x^(n-1) olarak hesaplar ve sabit çarpan kuralını uygular.",
                description_en="Apply power rule, constant multiple rule, and sum/difference rules to differentiate polynomials.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-2.5",
                curriculum="AP_CALC",
                node_id="N90",
                title_tr="Kuvvet Kuralı",
                title_en="Applying the Power Rule",
                description_tr="Kuvvet kuralını pozitif, negatif ve kesirli üsler için uygular.",
                description_en="Differentiate powers of x for all real exponents.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.6.1.3",
                curriculum="MEB",
                node_id="N91",
                title_tr="Çarpımın Türevi Kuralı",
                title_en="The Product Rule for Derivatives",
                description_tr="İki fonksiyonun çarpımının türev kuralını (f'g + fg') uygular.",
                description_en="Differentiate products of two differentiable functions using (uv)' = u'v + uv'.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.6.1.4",
                curriculum="MEB",
                node_id="N92",
                title_tr="Bölümün Türevi Kuralı",
                title_en="The Quotient Rule for Derivatives",
                description_tr="İki fonksiyonun bölümünün türev kuralını uygular, işaret hatasından kaçınır.",
                description_en="Apply quotient rule ((u'v - uv')/v^2) accurately.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.6.2.1",
                curriculum="MEB",
                node_id="N94",
                title_tr="Bileşke Fonksiyonun Türevi (Zincir Kuralı)",
                title_en="Chain Rule for Composite Functions",
                description_tr="Bileşke fonksiyonların türevinde dış ve iç türev çarpım kuralını uygular.",
                description_en="Differentiate composite functions by multiplying outer derivative by inner derivative.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-3.1",
                curriculum="AP_CALC",
                node_id="N94",
                title_tr="Zincir Kuralı",
                title_en="The Chain Rule",
                description_tr="İç türev faktörünü eksiksiz kullanarak bileşke fonksiyonları diferansiyeller.",
                description_en="Calculate derivatives of composite functions systematically using the Chain Rule.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.6.2.2",
                curriculum="MEB",
                node_id="N95",
                title_tr="Trigonometrik Fonksiyonların Türevleri",
                title_en="Derivatives of Trigonometric Functions",
                description_tr="sin(x), cos(x), tan(x) fonksiyonlarının türevlerini ve işaretlerini uygular.",
                description_en="Find derivatives of basic trigonometric functions, verifying negative signs for cos and cot.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.6.2.3",
                curriculum="MEB",
                node_id="N96",
                title_tr="Üstel ve Logaritmik Fonksiyonların Türevleri",
                title_en="Derivatives of Exponential and Logarithmic Functions",
                description_tr="e^x, a^x, ln(x), log_a(x) türevlerini zincir kuralı ile birleştirir.",
                description_en="Differentiate exponential (e^x, a^x) and logarithmic (ln x, log_a x) functions.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.6.3.1",
                curriculum="MEB",
                node_id="N97",
                title_tr="Teğet ve Normal Doğrularının Denklemleri",
                title_en="Tangent and Normal Lines",
                description_tr="Eğrinin verilen noktadaki teğet ve normal denklemini türev yardımıyla kurar.",
                description_en="Determine equations of tangent and normal lines to a curve at a given point.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.6.3.2",
                curriculum="MEB",
                node_id="N98",
                title_tr="L'Hôpital Kuralı",
                title_en="L'Hôpital's Rule for Indeterminate Forms",
                description_tr="0/0 ve inf/inf limitlerinde pay ve paydanın ayrı ayrı türevini alarak limiti çözer.",
                description_en="Apply L'Hôpital's Rule by differentiating numerator and denominator independently.",
                grade_level="12",
            ),
            # SEVİYE 12: Türev Uygulamaları & Optimizasyon (N99 - N110)
            CurriculumStandard(
                standard_id="MEB-12.6.4.1",
                curriculum="MEB",
                node_id="N99",
                title_tr="Ortalama Değer Teoremi ve Rolle Teoremi",
                title_en="Mean Value Theorem and Rolle's Theorem",
                description_tr="Kapalı aralıkta sürekli, açık aralıkta türevlenebilir fonksiyonlar için MVT uygular.",
                description_en="State and apply Rolle's Theorem and the Mean Value Theorem on given intervals.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-5.1",
                curriculum="AP_CALC",
                node_id="N99",
                title_tr="Ortalama Değer Teoremi Uygulamaları",
                title_en="Using the Mean Value Theorem",
                description_tr="Anlık değişim oranının ortalama değişim oranına eşitlendiği noktaları bulur.",
                description_en="Justify existence of tangent lines parallel to secant lines using MVT.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.6.4.2",
                curriculum="MEB",
                node_id="N100",
                title_tr="Artan ve Azalan Aralıkların İncelenmesi",
                title_en="Increasing and Decreasing Intervals",
                description_tr="Birinci türevin işaret tablosu yardımıyla fonksiyonun monotonluk aralıklarını belirler.",
                description_en="Determine intervals where a function is strictly increasing or decreasing using f'(x).",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.6.4.3",
                curriculum="MEB",
                node_id="N102",
                title_tr="Birinci Türev Testi ve Yerel Ekstremumlar",
                title_en="First Derivative Test for Local Extrema",
                description_tr="f'(x)'in işaret değiştirdiği noktalarda yerel maksimum ve minimumları tespit eder.",
                description_en="Locate local extrema using sign changes in the first derivative.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="IB-AA-SL-5.9",
                curriculum="IB_AA",
                node_id="N102",
                title_tr="Ekstremum Noktaları ve Türev Analizi",
                title_en="Stationary Points and Local Extrema",
                description_tr="Durağan noktaları sınıflandırır (maksimum, minimum, büküm).",
                description_en="Identify stationary points and classify them as local maxima, minima, or inflections.",
                grade_level="DP1",
            ),
            CurriculumStandard(
                standard_id="MEB-12.6.4.4",
                curriculum="MEB",
                node_id="N103",
                title_tr="İkinci Türev, Konkavlık ve Büküm Noktası",
                title_en="Second Derivative, Concavity, and Inflection Points",
                description_tr="f''(x)'in işaretine göre eğrilik yönünü ve işaret değiştirdiği büküm noktasını bulur.",
                description_en="Analyze concavity and determine points of inflection using the second derivative.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.6.5.1",
                curriculum="MEB",
                node_id="N105",
                title_tr="Maksimum ve Minimum (Optimizasyon) Problemleri",
                title_en="Optimization Problems",
                description_tr="Geometrik ve gerçek hayat modellerinde amaç fonksiyonu kurup türevle optimize eder.",
                description_en="Model real-world geometric problems and find optimal dimensions using differentiation.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-5.11",
                curriculum="AP_CALC",
                node_id="N105",
                title_tr="Optimizasyon Problemlerini Çözme",
                title_en="Solving Optimization Problems",
                description_tr="Kısıt denklemlerini kullanarak tek değişkenli optimizasyon fonksiyonu oluşturur.",
                description_en="Formulate and solve constraint-based optimization models in geometric contexts.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-3.2",
                curriculum="AP_CALC",
                node_id="N108",
                title_tr="Kapalı Fonksiyon Türevi",
                title_en="Implicit Differentiation",
                description_tr="F(x, y) = 0 biçimindeki denklemlerde dy/dx türevini zincir kuralı ile çözer.",
                description_en="Find dy/dx for equations defining y implicitly in terms of x using the chain rule.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-4.1",
                curriculum="AP_CALC",
                node_id="N109",
                title_tr="Bağlı Değişim Oranları",
                title_en="Related Rates of Change",
                description_tr="Zamana göre değişen bağıntılı değişkenlerin türevsel değişim hızlarını hesaplar.",
                description_en="Solve word problems involving related rates of change with respect to time.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-4.6",
                curriculum="AP_CALC",
                node_id="N110",
                title_tr="Doğrusal Yaklaşıklık ve Yerel Doğrusallık",
                title_en="Linear Approximations and Differentials",
                description_tr="Teğet doğrusunu kullanarak fonksiyon değerlerinin yaklaşık hesabını yapar.",
                description_en="Use local linear approximation (tangent line approximation) to estimate function values.",
                grade_level="Grade 11-12",
            ),
            # SEVİYE 13 & 14: Kalkülüs II — İntegral ve Alan Hesabı (N111 - N135)
            CurriculumStandard(
                standard_id="MEB-12.7.1.1",
                curriculum="MEB",
                node_id="N111",
                title_tr="Belirsiz İntegral ve Ters Türev",
                title_en="Indefinite Integral and Antiderivatives",
                description_tr="Ters türev kavramını açıklar ve belirsiz integrali integrasyon sabitiyle ifade eder.",
                description_en="Define antiderivatives and indefinite integrals, explaining the constant of integration (+C).",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-6.7",
                curriculum="AP_CALC",
                node_id="N111",
                title_tr="Belirsiz İntegral Kuralları ve Gösterimi",
                title_en="Finding Antiderivatives and Indefinite Integrals",
                description_tr="Temel ters türev kurallarını ve integrasyon sabitini uygular.",
                description_en="Determine indefinite integrals applying basic antidifferentiation rules and notation.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.7.1.2",
                curriculum="MEB",
                node_id="N112",
                title_tr="İntegralde Kuvvet Kuralı",
                title_en="Power Rule of Integration",
                description_tr="x^n fonksiyonunun integralini n != -1 için hesaplar.",
                description_en="Apply the power rule for integration for all exponents n != -1.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-6.8",
                curriculum="AP_CALC",
                node_id="N112",
                title_tr="Kuvvet Kuralı ile İntegrasyon",
                title_en="Integrating Using the Power Rule",
                description_tr="Polinom ve kuvvet fonksiyonlarını integre eder.",
                description_en="Integrate polynomial and power functions using antidifferentiation power rules.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.7.1.3",
                curriculum="MEB",
                node_id="N113",
                title_tr="1/x Fonksiyonunun İntegrali",
                title_en="Integration of Reciprocal Functions",
                description_tr="1/x fonksiyonunun integralini ln|x| + C olarak belirler.",
                description_en="Recognize that the integral of 1/x is ln|x| + C.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.7.1.4",
                curriculum="MEB",
                node_id="N115",
                title_tr="Trigonometrik İntegraller",
                title_en="Integrating Trigonometric Functions",
                description_tr="sin(x) ve cos(x) fonksiyonlarının integrallerini işaretlerine dikkat ederek hesaplar.",
                description_en="Integrate basic trigonometric functions, verifying negative signs for sin.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.7.2.1",
                curriculum="MEB",
                node_id="N117",
                title_tr="Değişken Değiştirme Yöntemi (u-Dönüşümü)",
                title_en="Integration by Substitution",
                description_tr="Bileşke integrallerde u = g(x) dönüşümü yaparak integrali hesaplar.",
                description_en="Integrate composite functions using u-substitution and differential replacement.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-6.9",
                curriculum="AP_CALC",
                node_id="N117",
                title_tr="u-Dönüşümü ile İntegrasyon",
                title_en="Integrating Using Substitution",
                description_tr="Zincir kuralının tersi olarak değişken değiştirme yöntemini uygular.",
                description_en="Apply substitution techniques to transform complex integrands into standard forms.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="IB-AA-SL-5.12",
                curriculum="IB_AA",
                node_id="N117",
                title_tr="Değişken Değiştirme ile İntegral",
                title_en="Integration by Substitution in IB Math",
                description_tr="u-dönüşümü ile analitik integralleri çözer.",
                description_en="Perform analytical integration using substitution method.",
                grade_level="DP2",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-6.11",
                curriculum="AP_CALC",
                node_id="N119",
                title_tr="Kısmi İntegrasyon Yöntemi",
                title_en="Integration by Parts",
                description_tr="Çarpım türevinin tersi olarak int u dv = uv - int v du kuralını uygular.",
                description_en="Apply integration by parts to evaluate products of algebraic and transcendental functions.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="IB-AA-HL-5.13",
                curriculum="IB_AA",
                node_id="N119",
                title_tr="Kısmi İntegrasyon",
                title_en="Integration by Parts (HL)",
                description_tr="Kısmi integrasyon algoritmasını uygular.",
                description_en="Evaluate integrals using repeated integration by parts.",
                grade_level="DP2",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-6.12",
                curriculum="AP_CALC",
                node_id="N120",
                title_tr="Basit Kesirlere Ayırma ile İntegral",
                title_en="Integration Using Partial Fractions",
                description_tr="Rasyonel fonksiyonları basit kesirlerine ayırarak logaritmik integral alır.",
                description_en="Integrate rational functions using partial fraction decomposition.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.7.3.1",
                curriculum="MEB",
                node_id="N123",
                title_tr="Riemann Toplamı ve Alan Sezgisi",
                title_en="Riemann Sums and Area Approximation",
                description_tr="Eğrinin altındaki alanı alt ve üst Riemann dikdörtgen toplamları ile yaklaşık hesaplar.",
                description_en="Approximate area under a curve using left, right, and midpoint Riemann sums.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-6.2",
                curriculum="AP_CALC",
                node_id="N123",
                title_tr="Riemann Toplamları ile Alan Yaklaşımı",
                title_en="Approximating Areas with Riemann Sums",
                description_tr="Alt, üst ve yamuk kuralı ile alan yaklaşımları üretir.",
                description_en="Estimate definite integrals using tabular data and Riemann sums.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-6.4",
                curriculum="AP_CALC",
                node_id="N125",
                title_tr="Kalkülüsün Temel Teoremi 1",
                title_en="The Fundamental Theorem of Calculus Part 1",
                description_tr="İntegral ile tanımlanan birikim fonksiyonlarının türevini alır.",
                description_en="Differentiate accumulation functions defined by definite integrals.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.7.3.2",
                curriculum="MEB",
                node_id="N126",
                title_tr="Belirli İntegral ve Temel Teorem",
                title_en="Definite Integrals and Fundamental Theorem",
                description_tr="Belirli integrali F(b) - F(a) bağıntısıyla analitik hesaplar.",
                description_en="Evaluate definite integrals analytically using the Fundamental Theorem of Calculus Part 2.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-6.6",
                curriculum="AP_CALC",
                node_id="N126",
                title_tr="Kalkülüsün Temel Teoremi 2",
                title_en="Fundamental Theorem of Calculus Part 2",
                description_tr="Belirli integrali ters türevlerin farkı olarak çözer.",
                description_en="Calculate definite integrals using antiderivative evaluation F(b) - F(a).",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="IB-AA-SL-5.11",
                curriculum="IB_AA",
                node_id="N126",
                title_tr="Belirli İntegral",
                title_en="Definite Integrals in IB AA",
                description_tr="Belirli integralin analitik çözümü ve özellikleri.",
                description_en="Evaluate definite integrals and apply linearity properties.",
                grade_level="DP2",
            ),
            CurriculumStandard(
                standard_id="MEB-12.7.4.1",
                curriculum="MEB",
                node_id="N129",
                title_tr="Belirli İntegral ile Alan Hesabı",
                title_en="Area Under a Curve Using Definite Integrals",
                description_tr="Fonksiyon grafiği ile x-ekseni arasında kalan alanı belirli integral ile hesaplar.",
                description_en="Calculate positive geometric area bounded by a curve and coordinate axes.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-8.4",
                curriculum="AP_CALC",
                node_id="N129",
                title_tr="Eğriler Arasındaki Alan",
                title_en="Finding Area Under Curves as Functions of x",
                description_tr="Belirli integral yardımıyla eğrilerin çevrelediği alanı bulur.",
                description_en="Set up and evaluate definite integrals representing area between curves.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="MEB-12.7.4.2",
                curriculum="MEB",
                node_id="N131",
                title_tr="İki Eğri Arasında Kalan Alan",
                title_en="Area Between Two Curves",
                description_tr="İki eğrinin kesim noktalarını bulup üst eğriden alt eğriyi çıkararak alanı bulur.",
                description_en="Find enclosed area between intersecting curves using upper minus lower functions.",
                grade_level="12",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-8.9",
                curriculum="AP_CALC",
                node_id="N133",
                title_tr="Dönel Cisimlerin Hacmi (Disk Yöntemi)",
                title_en="Volumes of Solids of Revolution (Disk Method)",
                description_tr="Bir eğrinin eksen etrafında döndürülmesiyle oluşan cismin hacmini hesaplar.",
                description_en="Compute volumes of revolution about horizontal and vertical axes using disk cross-sections.",
                grade_level="Grade 11-12",
            ),
            CurriculumStandard(
                standard_id="IB-AA-HL-5.14",
                curriculum="IB_AA",
                node_id="N133",
                title_tr="Dönel Cisim Hacmi",
                title_en="Volumes of Revolution (HL)",
                description_tr="Eksen etrafında döndürme hacmini integre eder.",
                description_en="Calculate volumes of revolution about coordinate axes.",
                grade_level="DP2",
            ),
            CurriculumStandard(
                standard_id="AP-CALC-6.13",
                curriculum="AP_CALC",
                node_id="N135",
                title_tr="Genelleştirilmiş (Has Olmayan) İntegraller",
                title_en="Evaluating Improper Integrals",
                description_tr="Sonsuz sınırlara sahip integrallerin yakınsaklık ve ıraksaklığını limit ile inceler.",
                description_en="Evaluate improper integrals with infinite limits of integration using limits.",
                grade_level="Grade 11-12",
            ),
        ]

        for s in raw_standards:
            if s.curriculum not in self._standards:
                self._standards[s.curriculum] = []
            self._standards[s.curriculum].append(s)

    def get_standards_for_curriculum(self, curriculum: str) -> List[CurriculumStandard]:
        return self._standards.get(curriculum.upper(), [])

    def get_standard_for_node(self, node_id: str, curriculum: str) -> Optional[CurriculumStandard]:
        standards = self.get_standards_for_curriculum(curriculum)
        for s in standards:
            if s.node_id == node_id:
                return s
        return None

    def get_all_standards(self) -> List[CurriculumStandard]:
        all_std = []
        for std_list in self._standards.values():
            all_std.extend(std_list)
        return all_std
